### ISSUE TITLE
A way to load the Shell library with an alias in gjs.

### ISSUE THREAD

**Issue by lestcape** [lestcape/Classic-Gnome#20]
A way to load the Shell library with an alias in gjs.

The global problem is that, we want to load a cinnamon extension inside gnome shell without change the extension, but instead we want to create a save enviroment to the cinnamon extension to be loaded. We resolved most of problems, but there are others that i can not resolved yet.

We have one specific problem:

I need to import things that not really exist, but there are an equivalent version of that things in the shell.

For example a cinnamon extension is waiting for import the Cinnamon share library but the library that i really have as an equivalent is the Shell share library. So, need to load the Shell library apply some cinnamon specific patches and return it to the cinnamon extension.

An example of current instruction:
const Cinnamon = imports.gi.Cinnamon;

So, i need:
imports.gi.Cinnamon = imports.gi.Shell + some modifications;
To not break the cinnamon extension when it will run inside the shell. 

How we can do that?

**Comment by lestcape** [comment]
@ptomato if you have a time to help me, because this is a pure gjs and i think this is possible, thank anyway.

**Comment by lestcape** [comment]
This api work inside the shell, and is pretty useful for that: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy
```
let gi = new Proxy({}, {
        get : function(obj, prop) {
            if(prop === "Cinnamon") {
                return global._real_gi["Shell"];
            } else if(global._real_gi[prop] !== undefined) {
                return global._real_gi[prop];
            } else {
                return undefined;
            }
        }
    });
    global._real_gi = imports.gi;
    imports.gi = gi;

   // And now we can do safely, and will work!!!
   const Cinnamon = imports.gi.Cinnamon;
```

**Comment by lestcape** [comment]
@ptomato thanks anyway.

**Comment by ptomato** [comment]
Glad you were able to solve it.

You might be able to simplify it even more by using `Reflect` and making `imports.gi` the proxy target:
```js
let gi = new Proxy(imports.gi, {
    get(target, prop, proxy) {
        if (prop === 'Cinnamon')
            return target.Shell;
        return Reflect.get(target, prop);
    }
});
imports.gi = gi;
```
But I didn't test to see if that works.

**Comment by lestcape** [comment]
Ups, but i really want to return the things to the normal state some day :)

I did not even know that we also have a Reflect statics class that is a little more useful than the Object statically methods.

Really thanks...

**Comment by lestcape** [comment]
I just want to say really thanks for all your enforces, you probably won't have all the credit you deserve for doing something without interface.

I love the GJS idea and also I read that you want that gjs will be a better language than python and Vala for desktop applications. Something difficult but not impossible, as you already demostrate that is possible for me with the last release.

In my modest opinion, the port of gjs to mozjs52, enhanced the whole shell. Is a not nice that we don't have a tools to test a measure of how Gjs improve in performance with the change. Also what really this improve the performance of the shell. In my point of view, the change in gjs was impacted in the shell performance directly and is remarkable. Also when features like multi-threading are not used yet. The improve of the engenier alone justify the improve of the shell.

Some people think that was just the improve of mutter, but i don't belive that what i can see was just the mutter improve for particular areas. I need to recognize they all make good changes, but your changes in gjs is the only thing that justify that big enacement of the whole shell performance in my personal opinion.

A lot of people also think that gjs is slow and can not used to make a shell, just because is javascript. The problem really is in the architecture of the shell, not gjs, i know and hope this also will be fixed soon.

I wish you a good day and many more triumphs like this. Really thanks for your hard work.

**Comment by ptomato** [comment]
Thanks for your kind message. I really appreciate that you took the time to write that.

I would also like to have better performance tools. If you have any ideas or have examples of performance tools you've worked with before, I hope you will consider contributing!

**Comment by lestcape** [comment]
I have not experience on testing things, but for me is pretty interesting have a way to measure all. 

The introdution of the support for hidpi in cinnamon, was the cause a whole of performance reductions and I did not have a way to measure and prove my theory about it, luckily others also noticed it. Now In cinnamon they take the desktop loading time from the first gjs instruction to the last one, in the process of loading the desktop. That can give us some idea of how things are but just if your interest is to improve the shell, but not if you want only to know the performance of gjs.

Maybe i can create an extension, that could be able to startup a gjs service outside the compositor and raise at user request some test and then return back the resulting information to the the extension to then be displayed.

I think the most interesting tests for gjs could be:
   - Arithmetic operations
   - Object construction
   - GObject construction
   - Clutter allocation
   - Gtk allocation

I will see if i have a time to do something like that, but it will not be really scientific or nice.

Maybe is a good idea to take a look to the firefox code of his devtools, to see if is possible reuse it some how:
https://developer.mozilla.org/en-US/docs/Tools/Performance/Waterfall
